# Generated by Django 3.1.4 on 2021-03-23 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_id', models.IntegerField(max_length=11)),
                ('key_word', models.CharField(max_length=20)),
                ('related_word', models.CharField(max_length=20)),
                ('second', models.SmallIntegerField(max_length=6)),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(max_length=11)),
                ('plan_name', models.CharField(max_length=20)),
                ('total_score', models.SmallIntegerField(max_length=6)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(max_length=11)),
                ('user_id', models.IntegerField(max_length=11)),
                ('record_name', models.CharField(max_length=20)),
                ('extension_name', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=5)),
                ('duration', models.SmallIntegerField(max_length=6)),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(max_length=11)),
                ('plan_id', models.IntegerField(max_length=11)),
                ('user_id', models.IntegerField(max_length=11)),
                ('inspection_time', models.DateTimeField(default=datetime.datetime(2021, 3, 23, 16, 57, 6, 880832), verbose_name='质检日期')),
                ('score', models.SmallIntegerField(max_length=11)),
                ('key1', models.CharField(max_length=20)),
                ('key2', models.CharField(max_length=20)),
                ('key3', models.CharField(max_length=20)),
                ('rating_details', models.CharField(max_length=252)),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('role_level', models.SmallIntegerField(max_length=6)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_id', models.CharField(max_length=20)),
                ('series_name', models.CharField(max_length=20)),
                ('series_type', models.IntegerField(max_length=11)),
                ('series_score', models.SmallIntegerField(max_length=6)),
                ('everyhit_score', models.SmallIntegerField(max_length=6)),
                ('frequency', models.SmallIntegerField(max_length=6)),
            ],
            options={
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(max_length=11)),
                ('task_name', models.CharField(max_length=20)),
                ('last_time', models.DateTimeField(default=datetime.datetime(2021, 3, 23, 16, 57, 6, 881830), verbose_name='新建日期')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(max_length=11, null=True)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('parent_id', models.IntegerField(max_length=11, null=True)),
                ('mark', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
