# Generated by Django 3.1.4 on 2021-03-23 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 17, 4, 9, 319711), verbose_name='修改日期'),
        ),
        migrations.AddField(
            model_name='record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 17, 4, 9, 320707), verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='result',
            name='inspection_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 17, 4, 9, 320707), verbose_name='质检日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 17, 4, 9, 321704), verbose_name='新建日期'),
        ),
    ]
