# Generated by Django 3.1.4 on 2021-03-25 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityApp', '0006_auto_20210323_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 10, 23, 127616), verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 10, 23, 127616), verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='result',
            name='inspection_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 10, 23, 128614), verbose_name='质检日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 10, 23, 129611), verbose_name='新建日期'),
        ),
    ]
