# Generated by Django 3.1.4 on 2021-03-25 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityApp', '0007_auto_20210325_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 11, 12, 197140), verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 11, 12, 197140), verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='result',
            name='inspection_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 11, 12, 198137), verbose_name='质检日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 11, 12, 199135), verbose_name='新建日期'),
        ),
    ]
