# Generated by Django 3.1.4 on 2021-03-25 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityApp', '0008_auto_20210325_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='series_keyword',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 12, 9, 330803), verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 12, 9, 331801), verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='result',
            name='inspection_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 12, 9, 331801), verbose_name='质检日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 9, 12, 9, 332798), verbose_name='新建日期'),
        ),
    ]
