# Generated by Django 3.1.4 on 2021-04-14 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityApp', '0009_auto_20210325_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 15, 40, 57, 528978), verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 15, 40, 57, 528978), verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='result',
            name='inspection_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 15, 40, 57, 529976), verbose_name='质检日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 15, 40, 57, 530973), verbose_name='新建日期'),
        ),
    ]
