# Generated by Django 3.1.4 on 2021-05-24 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityApp', '0010_auto_20210414_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=11)),
                ('extension_number', models.IntegerField(max_length=11, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 9, 34, 36, 533456), verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 9, 34, 36, 533456), verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='result',
            name='inspection_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 9, 34, 36, 534453), verbose_name='质检日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 9, 34, 36, 536447), verbose_name='新建日期'),
        ),
    ]
