# Generated by Django 3.1.4 on 2021-05-24 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityApp', '0011_auto_20210524_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='extension_number',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 9, 40, 49, 418889), verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 9, 40, 49, 418889), verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='result',
            name='inspection_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 9, 40, 49, 419872), verbose_name='质检日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 9, 40, 49, 419872), verbose_name='新建日期'),
        ),
    ]
